---
# Apache listeners.
- name: Delete Apache Listeners.
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: "^Listen"
    state: absent
  notify: restart apache

- name: Configure Apache listeners.
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    line: "Listen {{ item }}"
    state: present
  with_items:
    - "{{ apache_listeners }}"
    - "{{ apache_listen_ports }}"
  notify: restart apache

- name: Configure Apache listeners ssl.
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    line: "Listen {{ item }} https"
    state: present
  with_items:
    - "{{ apache_listen_ports_ssl }}"
  notify: restart apache

# Apache mods.
# TODO: add ssl module if ssl ports enabled

- name: Enable Apache mods.
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    line: "LoadModule {{ item }}_module modules/mod_{{ item }}.so"
    state: present
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Disable Apache mods.
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    line: "LoadModule {{ item }}_module modules/mod_{{ item }}.so"
    state: absent
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache

# Apache SSL.

# Apache vhosts.