---
# Delete all files from conf.d
- name: Find files in conf.d
  find:
    paths: "{{ apache_server_root }}/conf.d"
    patterns: "*"
  register: result

- name: Delete files from conf.d
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ result.files }}"

# Apache listeners.
- name: Delete Apache Listeners.
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: "^Listen"
    state: absent
  notify: restart apache

- name: Manages SELinux network port type definitions.
  seport:
    ports: "{{ item }}"
    setype: http_port_t
    proto: tcp
    state: present
  with_items:
    - "{{ apache_listen_ports }}"
    - "{{ apache_listen_ports_ssl }}"

- name: Configure Apache listeners.
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    line: "Listen {{ item }}"
    state: present
  with_items:
    - "{{ apache_listeners }}"
    - "{{ apache_listen_ports }}"
  notify: restart apache

- name: Configure Apache listeners ssl.
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    line: "Listen {{ item }} https"
    state: present
  with_items:
    - "{{ apache_listen_ports_ssl }}"
  notify: restart apache

# Apache mods.
- name: Add ssl module if ssl ports enabled
  set_fact:
    apache_mods_enabled: "{{ apache_mods_enabled | union(['ssl']) }}"
  when: apache_listen_ports_ssl | length > 0

- name: Enable Apache mods.
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    line: "LoadModule {{ item }}_module modules/mod_{{ item }}.so"
    state: present
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Disable Apache mods.
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    line: "LoadModule {{ item }}_module modules/mod_{{ item }}.so"
    state: absent
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache

# Apache SSL.

# Apache vhosts.