---
# Apache listeners.
apache_listeners: []
  # - 192.168.1.101:8090 https
apache_listen_ports:
  - 80
  - 8080
apache_listen_ports_ssl:
  - 443

# Apache mods.
apache_mods_enabled: []
apache_mods_disabled: []

# Apache SSL.
apache_ssl_certificate_file: ""
apache_ssl_certificate_keyfile: ""

apache_ssl_protocol: "All -SSLv2 -SSLv3"
apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"

# Apache vhosts.
apache_vhosts_filename: ""