---
- name: Delete old version of docker.
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ docker_old_packages }}"

- name: Install Docker dependencies.
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ docker_dependencies }}"

- name: Add Docker GPG key.
  rpm_key:
    key: "{{ docker_gpg_key }}"
    state: present

- name: Add Docker repository.
  get_url:
    url: "{{ docker_repository }}"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install Docker.
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ docker_packages }}"
